name: 同步内核仓库

on:
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: 检出源仓库
      uses: actions/checkout@v2
      with:
        repository: aosp-mirror/kernel_common
        ref: android12-5.10-lts

    - name: 设置 Git 用户信息
      run: |
        git config --global user.name 'PrintX'
        git config --global user.email '3042627767@qq.com'

    - name: 验证目标仓库 URL
      run: |
        echo "目标仓库: https://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@github.com/PrintX05/kernel.git"

    - name: 添加目标仓库和同步分支
      run: |
        git remote add target https://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@github.com/PrintX05/kernel.git
        git fetch target
        git checkout -B 5.10-lts origin/android12-5.10-lts

    - name: 强制推送更改到目标仓库的 5.10-lts 分支
      run: |
        git reset --hard origin/android12-5.10-lts
        git push https://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@github.com/PrintX05/kernel.git +HEAD:refs/heads/5.10-lts --force
